const PAST_TIME = `Can't have a match on a past time`
const MATCH_ALREADY_EXISTS = `Match is already exists`
const TEAM_ALREADY_PLAYED_THIS_ROUND = `Team already played this round`
const REFEREE_NOT_FOUND = `Referee not found`
const TEAM_NOT_FOUND = `Team not found`
const DIFFERENT_LEAGUES_TEAMS = `Can't have match of teams from different leagues`
const NO_MAIN_REFEREE = `Can't have match without main referee`
const REFEREE_ALREADY_SET_IN_THIS_MATCH = `Referee already set in this game`
const STADIUM_NOT_FOUND = `Stadium not found`
const ROUND_NOT_FOUND = `Round not found`
const REFEREE_ALREADY_SET_TO_MATCH_THIS_DAY = `Referee already set to a match on this day`
const INVALID_REFEREE_NAME = `referee name must contain first name and last name, seperated by 1 space, for example: AAAAA BBBBB`
const REFEREE_NAME_NOT_FOUND = `Referee name wasnt found`
const REFEREE_TYPE_NOT_LEGAL = 'Referee type must be either 1 or 0'
const REFEREE_NAME_ALREADY_EXISTS = 'Referee name aleardy exists'


exports.BAD_MATCH_TIME = BAD_MATCH_TIME;
exports.PAST_TIME = PAST_TIME;
exports.MATCH_ALREADY_EXISTS = MATCH_ALREADY_EXISTS;
exports.TEAM_ALREADY_PLAYED_THIS_ROUND = TEAM_ALREADY_PLAYED_THIS_ROUND;
exports.REFEREE_NOT_FOUND = REFEREE_NOT_FOUND;
exports.TEAM_NOT_FOUND = TEAM_NOT_FOUND;
exports.DIFFERENT_LEAGUES_TEAMS = DIFFERENT_LEAGUES_TEAMS;
exports.NO_MAIN_REFEREE = NO_MAIN_REFEREE
exports.REFEREE_ALREADY_SET_IN_THIS_MATCH = REFEREE_ALREADY_SET_IN_THIS_MATCH
exports.STADIUM_NOT_FOUND = STADIUM_NOT_FOUND
exports.ROUND_NOT_FOUND = ROUND_NOT_FOUND
exports.REFEREE_ALREADY_SET_TO_MATCH_THIS_DAY = REFEREE_ALREADY_SET_TO_MATCH_THIS_DAY
exports.INVALID_REFEREE_NAME = INVALID_REFEREE_NAME
exports.REFEREE_NAME_NOT_FOUND = REFEREE_NAME_NOT_FOUND
exports.REFEREE_TYPE_NOT_LEGAL = REFEREE_TYPE_NOT_LEGAL
exports.REFEREE_NAME_ALREADY_EXISTS = REFEREE_NAME_ALREADY_EXISTS